get_target_property (QMAKE_COMMAND Qt5::qmake IMPORTED_LOCATION)
execute_process (
    COMMAND ${QMAKE_COMMAND} -query QT_INSTALL_QML
    OUTPUT_VARIABLE QT_INSTALL_QML OUTPUT_STRIP_TRAILING_WHITESPACE
)
